version: '3.2'
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports: 
      - 5432:5432
