version: '3.2'
# Create networks to be used to isolate containers
networks:
  # Server network to hold database and backend
  servernetwork: {}
# Define services to be run.
services:
  database:
    image: mariadb:10.1
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=rosterviewer
    ports:
      - "3306:3306"
    networks:
      # Add the database service to the servernetwork.
      - servernetwork
  application:
    image: sharemyroster/application:latest
    build:
      context: ./
    volumes:
      - ./application:/application/code
    environment:
      - DATABASE_URL=mysql://root:@database:3306/rosterviewer
      - CONTACT_EMAIL=$CONTACT_EMAIL
    ports:
      - "3000:3000"
    networks:
      - servernetwork
    depends_on:
      - database