version: '3.2'
# Create networks to be used to isolate containers
networks:
  # Server network to hold database and backend
  servernetwork: {}
# Define services to be run.
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      ports: 5432
    networks:
      - servernetwork
  application:
    image: sharemyroster/application:latest
    build:
      context: ./
    volumes:
      - ./application:/application/code
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/docker
      - CONTACT_EMAIL=$CONTACT_EMAIL
    ports:
      - "3000:3000"
    networks:
      - servernetwork
    depends_on:
      - postgres
  phppgadmin:
    build: phppgadmin-docker
    ports:
      - 127.0.0.1:9080:80
    depends_on:
      - postgres
    environment:
      PPA_DEFAULTDB: docker
      PPA_HOST: postgres