version: 2.1
jobs:
  build_application:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/sharemyroster
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
      - checkout
      - run:
          name: Build application
          command: |
            yarn install
            yarn run build --release
      - run:
          name: Build docker image
          command: |
            docker build -t $DOCKER_REGISTRY/sharemyroster/application:latest .
      - run:
          name: Push image to repository
          command: |
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $DOCKER_REGISTRY/sharemyroster/application:latest $DOCKER_REGISTRY/sharemyroster/application:$CIRCLE_SHA1
            docker push $DOCKER_REGISTRY/sharemyroster/application:latest
            docker push $DOCKER_REGISTRY/sharemyroster/application:$CIRCLE_SHA1
  # test:
  #   machine: true
  #   working_directory: ~/sharemyroster
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run docker-login and docker-pull
  #         command: |
  #           docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
  #           docker-compose pull
  #     - run:
  #         name: Run docker-up & curl test
  #         command: |
  #           docker-compose up -d
  #           docker-compose exec application curl -4 --retry 10 --retry-delay 5 --retry-connrefused -v http://127.0.0.1:3000/
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl & Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
            mkdir ~/.kube/
            echo "$KUBECONFIG_BASE64" | base64 --decode > ~/.kube/config
      - run:
          name: Deploy Code
          command: |
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
            helm upgrade -n sharemyroster -i sharemyroster ./helm-chart/ --reuse-values --set application.image.version="$CIRCLE_SHA1"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_application
      # - test:
      #     requires:
      #       - build_application
      - deploy:
          requires:
            - build_application
