version: 2.1
jobs:
  build_application:
    docker:
      - image: circleci/node:stretch
    working_directory: ~/RosterViewer
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
      - checkout
      - run:
          name: Build Image & Register Task
          command: |
            yarn install
            yarn run build --release
            docker build -t $DOCKER_REGISTRY/rosterviewer/application:latest .
      - run:
          name: Build Image & Register Task
          command: |
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $DOCKER_REGISTRY/rosterviewer/application:latest $DOCKER_REGISTRY/rosterviewer/application:$CIRCLE_SHA1
            docker push $DOCKER_REGISTRY/rosterviewer/application:latest
            docker push $DOCKER_REGISTRY/rosterviewer/application:$CIRCLE_SHA1
  # test:
  #   machine: true
  #   working_directory: ~/RosterViewer
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run docker-login and docker-pull
  #         command: |
  #           docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
  #           docker-compose pull
  #     - run:
  #         name: Run docker-up & curl test
  #         command: |
  #           docker-compose up -d
  #           docker-compose exec application curl -4 --retry 10 --retry-delay 5 --retry-connrefused -v http://127.0.0.1:3000/
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: |
            chmod +x ./.circleci/kubernetes-deployment.sh
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
            ./.circleci/kubernetes-deployment.sh circleci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_application
      - test
      # - test:
      #     requires:
      #       - build_application
      # - deploy:
      #     requires:
      #       - test
