
{{- if .Values.database -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.fullname" . }}-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.fullname" . }}-database
      annotations:
        backup.velero.io/backup-volumes: {{ include "helm-chart.fullname" . }}-database
    spec:
      containers:
      - image: {{ .Values.database.image.repository }}:{{ .Values.database.image.version }}
        name: {{ include "helm-chart.fullname" . }}-database
        env:
        - name: POSTGRES_USER
          value: {{ include "helm-chart.fullname" . }}
        - name: POSTGRES_PASSWORD
          value: {{ include "helm-chart.fullname" . }}
        - name: POSTGRES_DB
          value: {{ include "helm-chart.fullname" . }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: {{ .Values.database.port }}
          name: database
        volumeMounts:
        - name: {{ include "helm-chart.fullname" . }}-database
          mountPath:  /var/lib/postgresql/data
      volumes:
        - name: {{ include "helm-chart.fullname" . }}-database
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}-database
{{- end }}