apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-application
  labels:
    app: {{ include "helm-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
    app: {{ include "helm-chart.fullname" . }}
    tier: application
