{{- if .Values.database -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-database
  labels:
    app: {{ include "helm-chart.fullname" . }}-database
spec:
  ports:
  - port: {{ .Values.database.port }}
  selector:
    app: {{ include "helm-chart.fullname" . }}-database
{{- end -}}