kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: default
spec:
  tls:
  - hosts:
      - www.sharemyroster.com
    secretName: www.sharemyroster.com-tls
  rules:
  - host: www.sharemyroster.com
    http:
      paths:
        - path: /
          backend:
            serviceName: rosterviewer-application-service
            servicePort: 3000